### ISSUE TITLE
Venda de veículos

### ISSUE THREAD

**Issue by JuliaMedeir0s** [JuliaMedeir0s/Sistema-de-compra-e-venda-de-veiculos#3]
Seu sistema também deve permitir a venda de veículos. Sempre que uma venda for efetuada, ela deve ser registrada no arquivo historico_vendas.csv e o veículo adquirido deve ser removido do arquivo veiculos_estoque.csv. Todo registro de venda deve conter data e hora atual.

**Comment by FelipeDev92** [comment]
Função venda de veículo:

Entrada:
struct veiculo v;
File estoque_veículo;
File marcas
File histórico de vendas;

Saída:


Descrição
Função recebe a struct veiculo v;
Procura o veículo em estoque_veiculo;
Aplica uma taxa no preço do veículo;
Envia a informação da venda para histórico_vendas;
Apaga o veículo em estoque_veiculo;
